# Generated by Django 4.2.3 on 2023-09-26 19:54

from django.db import migrations, models
import neobank.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(help_text='Account number must be ten digits.', max_length=10, primary_key=True, serialize=False, unique=True, validators=[neobank.common.validators.BankAccountNumberValidator()]),
        ),
        migrations.AlterField(
            model_name='historicalbankaccount',
            name='account_number',
            field=models.CharField(db_index=True, help_text='Account number must be ten digits.', max_length=10, validators=[neobank.common.validators.BankAccountNumberValidator()]),
        ),
    ]
