# Generated by Django 4.2.3 on 2023-09-23 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import neobank.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_baseuser_jwt_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseuser',
            name='first_name',
            field=models.CharField(default='--', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseuser',
            name='last_name',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identification', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, help_text='You must enter the telephone code, followed by a space and then the cell phone number. Ex: +57 3016789870', max_length=100, validators=[neobank.common.validators.PhoneRegexValidator()], verbose_name='Cell phone number')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='user_profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
