# Generated by Django 4.2.3 on 2023-09-25 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import neobank.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_baseuser_first_name_alter_baseuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='telephone',
            field=models.CharField(blank=True, help_text='You must enter the telephone code, followed by a space and then the cell phone number. Ex: +57 3016789870', max_length=100, validators=[neobank.common.validators.PhoneRegexValidator()]),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, help_text='You must enter the telephone code, followed by a space and then the cell phone number. Ex: +57 3016789870', max_length=100, validators=[neobank.common.validators.PhoneRegexValidator()]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
